# Generated by Django 5.1.4 on 2025-01-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(max_length=15)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Fix Deposit', 'Fix Deposit')], default='Savings', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
