# Generated by Django 5.1.4 on 2025-01-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_alter_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
