# Generated by Django 5.1.4 on 2025-01-09 10:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='sender_account',
        ),
        migrations.AddField(
            model_name='account',
            name='account_expiry',
            field=models.DateTimeField(default=datetime.datetime(2027, 10, 6, 10, 50, 6, 723177)),
        ),
        migrations.AddField(
            model_name='account',
            name='cvv',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Bank.account'),
        ),
    ]
