# Generated by Django 5.1.4 on 2025-01-09 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_rename_account_transaction_sender_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_expiry',
            field=models.DateTimeField(default=datetime.datetime(2027, 10, 6, 16, 21, 32, 98101)),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=10450222773217),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv',
            field=models.IntegerField(default=205),
        ),
    ]
