# Generated by Django 5.1.4 on 2025-01-09 16:24

import Bank.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0008_alter_account_account_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_expiry',
            field=models.DateTimeField(default=datetime.datetime(2027, 10, 6, 16, 24, 22, 510323)),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.BigIntegerField(default=Bank.models.generate_account_number),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv',
            field=models.IntegerField(default=Bank.models.generate_cvv),
        ),
    ]
